Run tests with sudo

diff --git a/.github/workflows/ci-sandbox.yml b/.github/workflows/ci-sandbox.yml
--- a/.github/workflows/ci-sandbox.yml
+++ b/.github/workflows/ci-sandbox.yml
@@ -189,7 +189,13 @@ jobs:
         run: |
           sysctl net.ipv4.ping_group_range
           id
-          ping -c 1 127.0.0.1 || echo "Ping failed"
+          ping -c 1 127.0.0.1 || echo "Ping localhost failed"
+          # Check ping to real interface
+          hostname -I
+          ping -c 1 $(hostname -I | awk '{print $1}') || echo "Ping real IP failed"
+          # Check ping capabilities
+          getcap /bin/ping || echo "No capabilities"
+          ls -la /bin/ping
 
   build_linux:
     runs-on: ${{ matrix.runner }}
@@ -237,20 +243,20 @@ jobs:
             apt_packages: clang-14 ninja-build python3-dev python3-numpy
             cmake_defines: -DCMAKE_C_COMPILER=clang-14 -DCMAKE_CXX_COMPILER=clang++-14 -DOPENDAQ_GENERATE_PYTHON_BINDINGS=OFF -DOPENDAQ_GENERATE_CSHARP_BINDINGS=OFF
 
-    container:
-      image: ubuntu:22.04
-      env:
-        TZ: Europe/Berlin
-        DEBIAN_FRONTEND: noninteractive
+    # container:
+    #   image: ubuntu:22.04
+    #   env:
+    #     TZ: Europe/Berlin
+    #     DEBIAN_FRONTEND: noninteractive
 
     steps:
-      - name: Install basic dependencies
-        run: |
-          apt-get update
-          apt-get install -y git openssh-client
+      # - name: Install basic dependencies
+      #   run: |
+      #     apt-get update
+      #     apt-get install -y git openssh-client
 
-      - name: Disable git safe directory checks
-        run : git config --global --add safe.directory '*'
+      # - name: Disable git safe directory checks
+      #   run : git config --global --add safe.directory '*'
 
       # TODO: Remove these 3 steps before merging to openDAQ/openDAQ
       - name: Checkout openDAQ
