Dump ICMP ping UID allowed Get docker image back to build_linux job

diff --git a/.github/workflows/ci-sandbox.yml b/.github/workflows/ci-sandbox.yml
--- a/.github/workflows/ci-sandbox.yml
+++ b/.github/workflows/ci-sandbox.yml
@@ -180,6 +180,17 @@ jobs:
           name: Unit Test Results (${{ matrix.name }})
           path: ${{ steps.build.outputs.gtest-xml-path || env.test_path }}
 
+  check_ping:
+    runs-on: ubuntu-latest
+    name: Check ping allowed
+
+    steps:
+      - name: Check ping permissions
+        run: |
+          sysctl net.ipv4.ping_group_range
+          id
+          ping -c 1 127.0.0.1 || echo "Ping failed"
+
   build_linux:
     runs-on: ${{ matrix.runner }}
     name: ${{ matrix.name }}
@@ -195,15 +206,16 @@ jobs:
       matrix:
         include:
           - name: Ubuntu 22.04 gcc-12 Release
-            runner: ubuntu-22.04
-            cmake_generator: Ninja
-            cmake_build_type: Release
-            cmake_defines: -DCMAKE_C_COMPILER=gcc-12 -DCMAKE_CXX_COMPILER=g++-12 -DDAQMODULES_PARQUET_RECORDER_MODULE=ON -DOPENDAQ_GENERATE_PYTHON_BINDINGS=OFF -DOPENDAQ_GENERATE_CSHARP_BINDINGS=OFF
-          - name: Ubuntu Latest gcc-12 Release
             runner: ubuntu-latest
             cmake_generator: Ninja
             cmake_build_type: Release
-            cmake_defines: -DCMAKE_C_COMPILER=gcc-12 -DCMAKE_CXX_COMPILER=g++-12 -DDAQMODULES_PARQUET_RECORDER_MODULE=ON  -DOPENDAQ_GENERATE_PYTHON_BINDINGS=OFF -DOPENDAQ_GENERATE_CSHARP_BINDINGS=OFF
+            apt_packages: g++-12 ninja-build python3-dev python3-numpy
+            cmake_defines: -DCMAKE_C_COMPILER=gcc-12 -DCMAKE_CXX_COMPILER=g++-12 -DDAQMODULES_PARQUET_RECORDER_MODULE=ON -DOPENDAQ_GENERATE_PYTHON_BINDINGS=OFF -DOPENDAQ_GENERATE_CSHARP_BINDINGS=OFF
+          # - name: Ubuntu Latest gcc-12 Release
+          #   runner: ubuntu-latest
+          #   cmake_generator: Ninja
+          #   cmake_build_type: Release
+          #   cmake_defines: -DCMAKE_C_COMPILER=gcc-12 -DCMAKE_CXX_COMPILER=g++-12 -DDAQMODULES_PARQUET_RECORDER_MODULE=ON  -DOPENDAQ_GENERATE_PYTHON_BINDINGS=OFF -DOPENDAQ_GENERATE_CSHARP_BINDINGS=OFF
           # - name: Ubuntu 22.04 gcc-12 Debug
           #   image: ubuntu:22.04
           #   cmake_generator: Ninja
@@ -218,13 +230,27 @@ jobs:
           #   apt_packages: g++-9
           #   cc: gcc-9
           #   cxx: g++-9
-          - name: Ubuntu Latest clang-16 Release
+          - name: Ubuntu 22.04 clang-14 Release
             runner: ubuntu-latest
             cmake_generator: Ninja
             cmake_build_type: Release
-            cmake_defines: -DCMAKE_C_COMPILER=clang-16 -DCMAKE_CXX_COMPILER=clang++-16 -DOPENDAQ_GENERATE_PYTHON_BINDINGS=OFF -DOPENDAQ_GENERATE_CSHARP_BINDINGS=OFF
+            apt_packages: clang-14 ninja-build python3-dev python3-numpy
+            cmake_defines: -DCMAKE_C_COMPILER=clang-14 -DCMAKE_CXX_COMPILER=clang++-14 -DOPENDAQ_GENERATE_PYTHON_BINDINGS=OFF -DOPENDAQ_GENERATE_CSHARP_BINDINGS=OFF
+
+    container:
+      image: ubuntu:22.04
+      env:
+        TZ: Europe/Berlin
+        DEBIAN_FRONTEND: noninteractive
 
     steps:
+      - name: Install basic dependencies
+        run: |
+          apt-get update
+          apt-get install -y git openssh-client
+
+      - name: Disable git safe directory checks
+        run : git config --global --add safe.directory '*'
 
       # TODO: Remove these 3 steps before merging to openDAQ/openDAQ
       - name: Checkout openDAQ
@@ -254,6 +280,7 @@ jobs:
           cmake-config-preset: ${{ env.cmake_preset }}
           cmake-config-args: ${{ matrix.cmake_defines }}
           cmake-build-type: ${{ matrix.cmake_build_type }}
+          additional-dependencies: ${{ matrix.apt_packages }}
           enable-tests: true
 
       - name: Upload test results
